application: cuisinesanssoucis
version: 1
runtime: python
api_version: 1

handlers:
- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /apple-touch-icon\.png
  static_files: img/apple-touch-icon.png
  upload: img/apple-touch-icon\.png
  
- url: .*
  script: main.py
